import com.nabobery.sdkgen.buildlogic.publication.Adr0008ProductArtifactIds
import kotlinx.validation.ApiValidationExtension
import kotlinx.validation.ExperimentalBCVApi
import org.gradle.api.publish.PublishingExtension
import org.gradle.api.publish.maven.MavenPublication
import org.gradle.api.tasks.bundling.Jar
import org.gradle.plugins.signing.SigningExtension

plugins {
    `maven-publish`
    signing
    id("org.jetbrains.kotlinx.binary-compatibility-validator")
    id("org.jetbrains.dokka")
}

group = "io.github.nabobery"

// ADR-0007 treats KLib dumps as required (if experimental, target-specific) ABI evidence. BCV keeps KLib
// validation off unless it is explicitly opted into, so without this block every `klibApiCheck` task reports
// SKIPPED and the build passes while producing no KLib evidence at all.
configure<ApiValidationExtension> {
    @OptIn(ExperimentalBCVApi::class)
    klib {
        enabled = true
    }
}

val signingKey = providers.environmentVariable("GPG_SIGNING_KEY")
val signingPassphrase = providers.environmentVariable("GPG_SIGNING_PASSPHRASE")
val releaseBuild = providers.gradleProperty("sdkgenRelease").map(String::toBoolean).orElse(false)

if (releaseBuild.get()) {
    check(signingKey.isPresent && signingPassphrase.isPresent) {
        "Release publication requires GPG_SIGNING_KEY and GPG_SIGNING_PASSPHRASE."
    }
}

// Plain `java-library` modules (the JVM convention plugin) do not automatically create a Maven
// publication. KMP modules and `java-gradle-plugin` modules already register their own
// publications, so this only fills the gap for `sdkgen.kotlin-jvm` consumers. ADR-0008 requires
// sources JARs on every published coordinate; KMP publications include them already, so only the
// pure-JVM modules (java-library and the Gradle plugin) need `withSourcesJar()` here.
plugins.withId("java") {
    configure<JavaPluginExtension> {
        withSourcesJar()
        if (plugins.hasPlugin("com.gradle.plugin-publish")) {
            withJavadocJar()
        }
    }
}
plugins.withId("java-library") {
    if (!plugins.hasPlugin("java-gradle-plugin")) {
        configure<PublishingExtension> {
            publications.create<MavenPublication>("maven") {
                from(components["java"])
            }
        }
    }
}

// ADR-0008 fixes the public Maven coordinates independently of each module's directory name.
// Kotlin/Gradle-plugin publications name themselves after `project.name`, so every publication's
// artifact ID is rewritten by substituting the desired base name for that prefix; per-target KMP
// publication suffixes (e.g. `-jvm`, `-iosarm64`) and the Gradle plugin marker publication
// (already named after the plugin id, per Gradle's own convention) are left untouched.
//
// The project-path -> artifactId map itself lives in Adr0008ProductArtifactIds (shared with
// StagedArtifactRepositoryScanner's staged-artifact target derivation) so the eight product
// coordinates cannot drift apart between publishing and staged-artifact inventory scanning.
Adr0008ProductArtifactIds.projectPathToArtifactId[project.path]?.let { desiredBaseArtifactId ->
    plugins.withId("maven-publish") {
        if (plugins.hasPlugin("com.gradle.plugin-publish")) {
            tasks.named<Jar>("javadocJar").configure {
                description = "Assembles API documentation generated by Dokka."
                dependsOn("dokkaGenerateHtml")
                from(layout.buildDirectory.dir("dokka/html"))
                isPreserveFileTimestamps = false
                isReproducibleFileOrder = true
            }
        }
        configure<PublishingExtension> {
            publications.withType<MavenPublication>().configureEach {
                pom {
                    name.set("Kotlin SDKGen ${desiredBaseArtifactId.removePrefix("kotlin-sdkgen-")}")
                    description.set("OpenAPI 3.1 Kotlin Multiplatform SDK generation and runtime support.")
                    url.set("https://github.com/nabobery/kotlin-sdkgen")
                    inceptionYear.set("2026")
                    licenses {
                        license {
                            name.set("The Apache License, Version 2.0")
                            url.set("https://www.apache.org/licenses/LICENSE-2.0.txt")
                            distribution.set("repo")
                        }
                    }
                    developers {
                        developer {
                            id.set("nabobery")
                            name.set("Avinash Changrani")
                            url.set("https://github.com/nabobery")
                        }
                    }
                    scm {
                        connection.set("scm:git:https://github.com/nabobery/kotlin-sdkgen.git")
                        developerConnection.set("scm:git:ssh://git@github.com/nabobery/kotlin-sdkgen.git")
                        url.set("https://github.com/nabobery/kotlin-sdkgen")
                    }
                    issueManagement {
                        system.set("GitHub")
                        url.set("https://github.com/nabobery/kotlin-sdkgen/issues")
                    }
                }

                // Signing tasks own their publication's complete artifact set. A distinct archive
                // output per publication prevents Gradle from treating one publication's signature
                // as an undeclared input to another publication's publish task.
                if (!name.endsWith("PluginMarkerMaven") && !plugins.hasPlugin("com.gradle.plugin-publish")) {
                    val publicationName = name
                    val javadocJar =
                        tasks.register<Jar>("${publicationName}DokkaJavadocJar") {
                            description = "Assembles API documentation generated by Dokka for $publicationName."
                            archiveClassifier.set("javadoc")
                            archiveFileName.set("$publicationName-${project.version}-javadoc.jar")
                            dependsOn("dokkaGenerateHtml")
                            from(layout.buildDirectory.dir("dokka/html"))
                            isPreserveFileTimestamps = false
                            isReproducibleFileOrder = true
                        }
                    artifact(javadocJar)
                }
            }
        }

        // Kotlin Multiplatform finalizes some native target artifact IDs in its own project-evaluated
        // callback. Rewrite them only after every project callback has completed so it cannot restore
        // default project-name prefixes (for example, core-iosarm64) afterward.
        val publicationProject = project
        gradle.projectsEvaluated {
            publicationProject.configure<PublishingExtension> {
                publications.withType<MavenPublication>().configureEach {
                    if (!name.endsWith("PluginMarkerMaven")) {
                        artifactId = artifactId.replaceFirst(project.name, desiredBaseArtifactId)
                    }
                }
            }
        }
    }
}

configure<SigningExtension> {
    isRequired = releaseBuild.get()
    if (signingKey.isPresent && signingPassphrase.isPresent) {
        useInMemoryPgpKeys(signingKey.get(), signingPassphrase.get())
        sign(extensions.getByType<PublishingExtension>().publications)
    }
}
